services:
  fitmaxxing:
    image: ghcr.io/nxxt00/fitmaxxing:latest
    container_name: fitmaxxing
    ports:
      - "3000:3000"
    volumes:
      - fitmaxxing-data:/app/data
    networks:
      - nginx_default
    restart: unless-stopped

volumes:
  fitmaxxing-data:

networks:
  nginx_default:
    external: true
